/*
 * ElevenLabs API Documentation
 *
 * This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://beta.elevenlabs.io. Our API is experimental so all endpoints are subject to change.
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type FeedbackResponseModel struct {
	ThumbsUp bool `json:"thumbs_up"`
	Feedback string `json:"feedback"`
	Emotions bool `json:"emotions"`
	InaccurateClone bool `json:"inaccurate_clone"`
	Glitches bool `json:"glitches"`
	AudioQuality bool `json:"audio_quality"`
	Other bool `json:"other"`
	ReviewStatus string `json:"review_status,omitempty"`
}
