/*
 * ElevenLabs API Documentation
 *
 * This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://beta.elevenlabs.io. Our API is experimental so all endpoints are subject to change.
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type VoiceResponseModel struct {
	VoiceId string `json:"voice_id"`
	Name string `json:"name"`
	Samples []SampleResponseModel `json:"samples"`
	Category string `json:"category"`
	FineTuning *FineTuningResponseModel `json:"fine_tuning"`
	Labels map[string]string `json:"labels"`
	Description string `json:"description"`
	PreviewUrl string `json:"preview_url"`
	AvailableForTiers []string `json:"available_for_tiers"`
	Settings *VoiceSettingsResponseModel `json:"settings"`
}
