/*
 * ElevenLabs API Documentation
 *
 * This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://beta.elevenlabs.io. Our API is experimental so all endpoints are subject to change.
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RecordingResponseModel struct {
	RecordingId string `json:"recording_id"`
	MimeType string `json:"mime_type"`
	SizeBytes int32 `json:"size_bytes"`
	UploadDateUnix int32 `json:"upload_date_unix"`
	Transcription string `json:"transcription"`
}
