/*
 * ElevenLabs API Documentation
 *
 * This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://beta.elevenlabs.io. Our API is experimental so all endpoints are subject to change.
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type FineTuningResponseModel struct {
	ModelId string `json:"model_id"`
	IsAllowedToFineTune bool `json:"is_allowed_to_fine_tune"`
	FineTuningRequested bool `json:"fine_tuning_requested"`
	FinetuningState string `json:"finetuning_state"`
	VerificationAttempts []VerificationAttemptResponseModel `json:"verification_attempts"`
	VerificationFailures []string `json:"verification_failures"`
	VerificationAttemptsCount int32 `json:"verification_attempts_count"`
	SliceIds []string `json:"slice_ids"`
}
